# EUT 2003, 2011 y 2024
## Carga y preparación esencial

Este notebook carga los tres ficheros armonizados, valida su estructura,
unifica tipos y categorías y genera el fichero intermedio utilizado por los
notebooks de análisis.

In [1]:
import sys
from pathlib import Path

import pandas as pd

PROJECT_DIR = Path.cwd().resolve()
if PROJECT_DIR.name == "Notebooks":
    PROJECT_DIR = PROJECT_DIR.parent
elif not (PROJECT_DIR / "CleanDataSets").exists():
    candidates = [parent for parent in PROJECT_DIR.parents if (parent / "CleanDataSets").exists()]
    if not candidates:
        raise FileNotFoundError("No se ha podido localizar la carpeta raiz V2.0")
    PROJECT_DIR = candidates[0]
COMMON_DIR = PROJECT_DIR / "PythonCommon"
if str(COMMON_DIR) not in sys.path:
    sys.path.insert(0, str(COMMON_DIR))

from eut_common import (
    DATA_FILES,
    PREPARED_DATA,
    load_harmonized_data,
    missing_summary,
    prepare_harmonized_data,
    save_prepared_data,
    validate_harmonized_datasets,
)

In [2]:
pd.set_option("display.max_columns", 120)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

### Carga de los ficheros armonizados

In [3]:
datasets = load_harmonized_data()

pd.DataFrame({
    "año": list(datasets),
    "fichero": [str(DATA_FILES[year]) for year in datasets],
    "filas": [len(data) for data in datasets.values()],
    "columnas": [data.shape[1] for data in datasets.values()],
})

    año                                            fichero  filas  columnas
0  2003  C:\Users\raulm\Desktop\Proyecto\V3\CleanDataSe...   6955        76
1  2011  C:\Users\raulm\Desktop\Proyecto\V3\CleanDataSe...   6471        76
2  2024  C:\Users\raulm\Desktop\Proyecto\V3\CleanDataSe...   8291        76

### Validación estructural

In [4]:
validate_harmonized_datasets(datasets)
print("Validaciones superadas para 2003, 2011 y 2024.")

Validaciones superadas para 2003, 2011 y 2024.

### Unión y preparación

In [5]:
eut = prepare_harmonized_data(datasets)
print(f"Filas totales: {len(eut):,}")
print(f"Columnas: {eut.shape[1]}")
eut.head()

Filas totales: 21,717
Columnas: 76

,encuesta_year,hogar_uid,persona_uid,id_hogar,n_pers,tramo_edad,sexo,nivel_estudios,situacion_laboral,estrato,estado_salud,trimestre,dia_semana,tipo_dia,internet_medicion,factor_elevacion,min_cuidados_personales,min_trabajo_remunerado,min_estudios,min_hogar_familia,min_voluntario_reuniones,min_vida_social_diversion,min_deportes_airelibre,min_aficiones_informatica,min_medios_comunicacion,min_trayectos_noespec,min_cp_dormir,min_cp_comer_beber,min_cp_higiene_salud,min_tr_actividad_laboral,min_tr_actividades_relacionadas,min_est_clases_formacion,min_est_estudio_tiempo_libre,min_hf_actividades_culinarias,min_hf_mantenimiento_hogar,min_hf_ropa,min_hf_jardineria_animales,min_hf_construccion_reparaciones,min_hf_compras_servicios,min_hf_gestiones_hogar,min_hf_cuidado_menores,min_hf_cuidado_adultos,min_vr_voluntariado_organizado,min_vr_ayuda_otros_hogares,min_vr_participacion_religion,min_vs_vida_social,min_vs_diversion_cultura,min_vs_ocio_pasivo,min_da_ejercicio_fisico,min_da_ejercicio_productivo,min_da_actividades_relacionadas,min_ai_arte_aficiones,min_ai_informatica,min_ai_juegos,min_mc_lectura,min_mc_television_video,min_mc_radio_grabaciones,min_tray_trabajo,min_tray_estudios,min_tray_hogar_familia,min_tray_voluntariado,min_tray_vida_social,min_tray_otro_ocio,min_tray_cambio_municipio,min_tray_otros_no_especificado,min_internet_total,min_internet_cuidados_personales,min_internet_trabajo_remunerado,min_internet_estudios,min_internet_hogar_familia,min_internet_voluntario_reuniones,min_internet_vida_social_diversion,min_internet_deportes_airelibre,min_internet_aficiones_informatica,min_internet_medios_comunicacion,min_internet_trayectos_noespec
0,2003,2003_09089,2003_09089_01,09089,01,65 o más,Hombre,Sec. primera etapa,Jubilado o prejubilado,Gran ciudad / Área densa,Bueno,Ene-Mar,Lunes-Jueves,Día habitual,Internet,951.14,680.00,0.00,0.00,160.00,0.00,330.00,120.00,0.00,0.00,150.00,560.00,90.00,30.00,0.00,0.00,0.00,0.00,90.00,70.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,330.00,0.00,0.00,100.00,0.00,20.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,30.00,120.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,2003,2003_09090,2003_09090_01,09090,01,45-64 años,Hombre,Educación superior,Ocupado,Gran ciudad / Área densa,Aceptable,Ene-Mar,Lunes-Jueves,Día habitual,Internet,992.45,480.00,520.00,0.00,160.00,0.00,0.00,70.00,80.00,10.00,120.00,400.00,70.00,10.00,520.00,0.00,0.00,0.00,20.00,110.00,0.00,0.00,0.00,0.00,0.00,30.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,70.00,0.00,0.00,80.00,0.00,0.00,10.00,0.00,0.00,60.00,0.00,60.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,2003,2003_09090,2003_09090_02,09090,02,45-64 años,Mujer,Educación superior,Ocupado,Gran ciudad / Área densa,Bueno,Ene-Mar,Lunes-Jueves,Día habitual,Internet,954.69,600.00,490.00,0.00,210.00,0.00,0.00,0.00,0.00,40.00,100.00,490.00,90.00,20.00,490.00,0.00,0.00,0.00,130.00,40.00,20.00,0.00,0.00,0.00,0.00,20.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,40.00,0.00,0.00,90.00,0.00,10.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,2003,2003_09090,2003_09090_03,09090,03,10-24 años,Hombre,Educación superior,Otra inactividad,Gran ciudad / Área densa,Bueno,Ene-Mar,Lunes-Jueves,Día inusual,Internet,"1,145.94",600.00,0.00,60.00,30.00,380.00,20.00,0.00,80.00,0.00,270.00,440.00,120.00,40.00,0.00,0.00,60.00,0.00,30.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,380.00,0.00,0.00,0.00,20.00,0.00,0.00,0.00,0.00,80.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,270.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,2003,2003_09090,2003_09090_04,09090,04,10-24 años,Hombre,Sec. segunda etapa,Otra inactividad,Gran ciudad / Área densa,Bueno,Ene-Mar,Lunes-Jueves,Día inusual,Internet,"1,130.61",740.00,0.00,420.00,60.00,0.00,0.00,0.00,90.00,0.00,130.00,610.00,90.00,40.00,0.00,0.00,420.00,0.00,10.00,20.00,30.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,60.00,30.00,0.00,0.00,0.00,0.00,0.00,130.00,0.00,0.00,0.00,0.00,0.00,0.00,30.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,30.00,0.00,0.00

### Diagnóstico de valores ausentes

In [6]:
missing_overall, missing_by_year = missing_summary(eut)
display(missing_overall)
display(missing_by_year)

                                    n_ausentes  pct_ausentes
min_internet_total                        6471         29.80
min_internet_trabajo_remunerado           6471         29.80
min_internet_cuidados_personales          6471         29.80
min_internet_hogar_familia                6471         29.80
min_internet_estudios                     6471         29.80
min_internet_deportes_airelibre           6471         29.80
min_internet_aficiones_informatica        6471         29.80
min_internet_voluntario_reuniones         6471         29.80
min_internet_vida_social_diversion        6471         29.80
min_internet_medios_comunicacion          6471         29.80
min_internet_trayectos_noespec            6471         29.80
nivel_estudios                             534          2.46
tipo_dia                                    10          0.05

encuesta_year                       2003  2011  2024
nivel_estudios                        24     0   510
tipo_dia                              10     0     0
min_internet_total                     0  6471     0
min_internet_cuidados_personales       0  6471     0
min_internet_trabajo_remunerado        0  6471     0
min_internet_estudios                  0  6471     0
min_internet_hogar_familia             0  6471     0
min_internet_voluntario_reuniones      0  6471     0
min_internet_vida_social_diversion     0  6471     0
min_internet_deportes_airelibre        0  6471     0
min_internet_aficiones_informatica     0  6471     0
min_internet_medios_comunicacion       0  6471     0
min_internet_trayectos_noespec         0  6471     0

### Exportación para los notebooks de análisis

In [7]:
output_path = save_prepared_data(eut)
print(f"Fichero preparado: {output_path}")
print(f"Dimensiones: {eut.shape[0]:,} filas x {eut.shape[1]} columnas")

Fichero preparado: C:\Users\raulm\Desktop\Proyecto\V3\CleanDataSets\eut_analisis_preparado.csv
Dimensiones: 21,717 filas x 76 columnas